uint64 timestamp

bool allow_ctrl

float32 phi
float32 theta
float32 psi

float32 p
float32 q
float32 r

float32 omega1_meas
float32 omega2_meas

float32 zd_x
float32 zd_y
float32 zd_z

float32 zd_dot_x
float32 zd_dot_y
float32 zd_dot_z

float32 zd_ddot_x
float32 zd_ddot_y
float32 zd_ddot_z

float32 u1_ref

float32 alpha_cf
float32 alpha_sf
float32 eta_u

float32 p_d
float32 q_d
float32 tau_x_d
float32 tau_y_d
float32 u1_cmd
float32 delta

float32 omega1_cmd
float32 omega2_cmd
